platform :ios, '9.0'
use_frameworks! 

def shared_pods
    pod 'Mantle'
    pod 'LBBlurredImage'
    pod 'TSMessages'
    pod 'ReactiveSwift', :git => 'https://github.com/ReactiveCocoa/ReactiveSwift.git'

end

 target 'SimpleWeather' do
     shared_pods
 end

target 'SimpleWeatherTests' do
    shared_pods
end
